class Actions:
    SEND_MESSAGE = 'send_message'
    TYPING_START = 'typing_start'
    TYPING_STOP = 'typing_stop'
    MESSAGE_READ = 'message_read'
    READ_ALL = 'read_all'
    MESSAGE_REACTION = 'message_reaction'
    EDIT_MESSAGE = 'edit_message'
    DELETE_MESSAGE = 'delete_message'
    TOGGLE_PIN = 'toggle_pin'
    PING = 'ping'

class Events:
    RECEIVE_MESSAGE = 'receive_message'
    MESSAGE_ACK = 'message_ack'
    MESSAGE_DELIVERED = 'message_delivered'
    MESSAGE_READ = 'message_read'
    READ_ALL_CONFIRM = 'read_all_confirm'
    MESSAGE_REACTIONS_UPDATED = 'message_reactions_updated'
    MESSAGE_EDITED = 'message_edited'
    MESSAGE_DELETED_EVERYONE = 'message_deleted_everyone'
    MESSAGE_DELETED_ME = 'message_deleted_me'
    MESSAGE_PIN_UPDATED = 'message_pin_updated'
    ONLINE_USERS = 'online_users'
    USER_ONLINE = 'user_online'
    USER_OFFLINE = 'user_offline'
    PONG = 'pong'
