from rest_framework import serializers
from django.contrib.auth import get_user_model
from .models import Profile

from django.contrib.auth.password_validation import validate_password

User = get_user_model()

class ProfileSerializer(serializers.ModelSerializer):
    class Meta:
        model = Profile
        fields = ['avatar', 'bio', 'is_online', 'last_seen']

class UserSerializer(serializers.ModelSerializer):
    profile = ProfileSerializer(read_only=True)

    class Meta:
        model = User
        fields = ['id', 'username', 'email', 'first_name', 'last_name', 'profile']

class SignupSerializer(serializers.ModelSerializer):
    password = serializers.CharField(write_only=True)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'first_name', 'last_name']
        
    def create(self, validated_data):
        user = User.objects.create_user(
            username=validated_data['username'],
            email=validated_data.get('email', ''),
            password=validated_data['password'],
            first_name=validated_data.get('first_name', ''),
            last_name=validated_data.get('last_name', '')
        )
        return user

class ChangePasswordSerializer(serializers.Serializer):
    old_password = serializers.CharField(required=True,write_only=True)
    # Validate the new password using Django's configured password validators
    # (minimum length, common password, numeric password, etc.).
    new_password = serializers.CharField(required=True,write_only=True,validators=[validate_password])

    # Verify that the old password provided by the user is correct
    # before allowing the password to be changed.
    def validate_old_password(self, value):
        user = self.context["request"].user

        if not user.check_password(value):
            raise serializers.ValidationError("Old password is incorrect.")

        return value

    def save(self, **kwargs):
        user = self.context["request"].user
        new_password = self.validated_data["new_password"]
        
        # Hash the password securely before saving it to the database.
        user.set_password(new_password) 
        user.save()

        return user
    
class ForgotPasswordSerializer(serializers.Serializer):
    # Accept the user's email address to initiate the password reset process.
    email = serializers.EmailField(required=True)

class ResetPasswordSerializer(serializers.Serializer):
    # Base64-encoded user ID received from the password reset link
    uid = serializers.CharField(required=True)
    
    # Secure password reset token generated by Django.
    token = serializers.CharField(required=True)
    
    # Accept the new password from the user.
    # write_only=True ensures it is never returned in API responses.
    new_password = serializers.CharField(write_only=True,required=True,)
