# Generated by Django 5.2.16 on 2026-07-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_last_seen_auto_now"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cover_photo",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
