# Generated by Django 5.2.16 on 2026-07-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_conversation_admin_conversation_is_group_and_more"),
        ("chat", "0005_mute"),
    ]

    operations = []
