# Generated by Django 5.2.16 on 2026-07-15 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_reaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="file",
        ),
        migrations.AddField(
            model_name="attachment",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attachment",
            name="file_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachment",
            name="file_url",
            field=models.CharField(default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="attachment",
            name="mime_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                related_name="administered_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="avatar",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="cover",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_for_users",
            field=models.ManyToManyField(
                blank=True, related_name="deleted_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="chat.message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="starred_by",
            field=models.ManyToManyField(
                blank=True, related_name="starred_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="voice_note",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
