# Generated by Django 6.0.6 on 2026-07-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_remove_attachment_file_attachment_file_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="client_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
