# Generated by Django 6.0.6 on 2026-07-16 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_message_client_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["seq_num", "created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="chat_messag_convers_3154fc_idx",
        ),
        migrations.AddField(
            model_name="message",
            name="seq_num",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "seq_num", "created_at"],
                name="chat_messag_convers_30984b_idx",
            ),
        ),
    ]
