# Generated by Django 6.0.7 on 2026-07-17 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_alter_message_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="archived_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="archived_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="pinned_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="pinned_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="unread_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="unread_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
